# Generated by Django 5.0.2 on 2024-03-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='token',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
